[platformio]
src_dir = ../../

[env:m5stack-gray-si7021]
platform = espressif32
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
lib_deps =
  m5stack/M5Stack
build_src_filter =
  -<*>
  +<examples/m5-temp-fan/main.cpp>
  +<runtimes/cpp/DecisionEngine.cpp>
